# Generated by Django 3.0.5 on 2020-05-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200502_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('BOOKS ', 'BOOKS'), ('LAB ACCESSORIES', 'LAB ACCESSORIES'), ('ELECTRONICS', 'ELECTRONICS'), ('OTHERS', 'OTHERS')], default='', max_length=20),
        ),
    ]
