# Generated by Django 3.0.5 on 2020-05-16 18:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200503_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='phone_no',
            field=models.CharField(default='', max_length=10, validators=[django.core.validators.RegexValidator(code='Invalid', message='Invalid mobile number entered', regex='^[6789][0-9]{9}$')]),
        ),
    ]
