# Generated by Django 3.0.5 on 2020-05-16 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_phone_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='phone_no',
        ),
    ]
